# Generated by Django 5.2.5 on 2025-09-01 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctors', to='custom_admin.admin'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['user_type'], name='users_user_ty_578f8f_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['user', 'is_used'], name='verificatio_user_id_a91428_idx'),
        ),
        migrations.AddIndex(
            model_name='emailverificationcode',
            index=models.Index(fields=['expires_at'], name='verificatio_expires_211f48_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['approval_status'], name='doctors_approva_18c078_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['specialization'], name='doctors_special_6661e0_idx'),
        ),
        migrations.AddIndex(
            model_name='doctor',
            index=models.Index(fields=['is_available'], name='doctors_is_avai_62f7a8_idx'),
        ),
    ]
