# Generated by Django 5.2.4 on 2025-08-03 00:44

import apps.shared.utils.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auditing', '0002_alter_recommendationaudit_reviewed_by'),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='approved_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'user__user_type': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_doctors', to='custom_admin.admin'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, error_messages={'unique': 'A user with this phone number already exists.'}, max_length=20, null=True, unique=True, validators=[apps.shared.utils.validators.validate_phone_number], verbose_name='Phone Number'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
