# Generated by Django 5.2.5 on 2025-09-02 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientprofile',
            name='sleep_hours',
            field=models.PositiveSmallIntegerField(default=6, help_text='Average daily sleep hours (0–24)', verbose_name='Sleep Hours'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='stress_level',
            field=models.CharField(choices=[('very_low', 'Very low'), ('low', 'Low'), ('moderate', 'Moderate'), ('high', 'High'), ('very_high', 'Very high')], default='very_low', max_length=20, verbose_name='Stress Level'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='patientprofile',
            name='sun_exposure',
            field=models.CharField(choices=[('minimal', 'Minimal (indoor most of day)'), ('light', 'Light (short outdoor periods)'), ('moderate', 'Moderate (regular outdoor activities)'), ('high', 'High (work/spend lots of time outdoors)'), ('very_high', 'Very high (beach, sports, etc.)')], default='minimal', max_length=20, verbose_name='Sun Exposure'),
            preserve_default=False,
        ),
    ]
