# Generated by Django 5.2.5 on 2025-09-02 22:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_patientprofile_sleep_hours_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patientprofile',
            name='lifestyle_factors',
        ),
    ]
