# Generated by Django 5.2.5 on 2025-09-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assessment',
            name='current_phase',
            field=models.CharField(choices=[('screening_condition', 'Screening Condition'), ('basic_info', 'Basic Info'), ('specific_condition', 'Specific Condition'), ('oiliness_assessment', 'Oiliness Assessment'), ('sensitivity_assessment', 'Sensitivity Assessment'), ('hydration_assessment', 'Hydration Assessment'), ('lifestyle', 'Lifestyle'), ('analysis', 'Analysis'), ('complete', 'Complete')], default='screening_condition', max_length=30),
        ),
        migrations.AlterField(
            model_name='assessment',
            name='started_at',
            field=models.DateTimeField(auto_now_add=True, help_text='Timestamp when the assessment was started.'),
        ),
    ]
