# Generated by Django 5.2.5 on 2025-09-02 13:56

import apps.shared.utils.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analysis', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skinanalysis',
            name='analysis_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], help_text='Status of the analysis process.', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='analyzed_at',
            field=models.DateTimeField(help_text='Timestamp when the analysis was performed.', null=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='confidence_score',
            field=models.FloatField(help_text='Overall confidence score for the analysis.', null=True, validators=[apps.shared.utils.validators.validate_confidence_score]),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='image_metadata',
            field=models.JSONField(help_text='JSON data containing image resolution, lighting, etc.', null=True),
        ),
        migrations.AlterField(
            model_name='skinanalysis',
            name='image_url',
            field=models.URLField(help_text='URL of the uploaded skin image.', null=True),
        ),
    ]
