# Generated by Django 5.2.4 on 2025-08-03 00:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='admin',
            table='admin',
        ),
    ]
