# Generated by Django 5.2.4 on 2025-08-03 00:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auditing', '0001_initial'),
        ('custom_admin', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recommendationaudit',
            name='reviewed_by',
            field=models.ForeignKey(help_text='Staff member who reviewed this recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='custom_admin.admin'),
        ),
    ]
